# Author: Mwangi George
# Github: https://github.com/mwangi-george/

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - mdap_db:/usr/src/sqlite/data

  frontend:
    build: ./frontend
    ports:
      - "3838:3838"
    depends_on:
      - backend

volumes:
  mdap_db:
